# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

from principale import Ui_principale
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 811, 501))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.165, y1:0.148136, x2:1, y2:1, stop:0 rgba(0, 88, 129, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(290, 60, 221, 41))
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 81 30pt \"Raleway ExtraBold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(240, 120, 371, 91))
        self.label_2.setStyleSheet("font: 57 48pt \"Zilla Slab Medium\";\n"
"color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(230, 240, 351, 101))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("border-radius:20px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/image.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.pushButto = QtWidgets.QPushButton(self.widget)
        self.pushButto.setGeometry(QtCore.QRect(340, 380, 111, 41))
        self.pushButto.setMouseTracking(True)
        self.pushButto.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(53, 161, 161);\n"
"color:rgb(255, 255, 255);\n"
"font: 75 16pt \"Tw Cen MT\";")
        self.pushButto.setObjectName("pushButto")
        self.label.raise_()
        self.label_2.raise_()
        self.pushButto.raise_()
        self.label_3.raise_()
        
        Dialog.setWindowIcon(QtGui.QIcon("interface\parking.png"))
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButto.clicked.connect(self.GoToPrincipal)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ParkingApp"))
        self.label.setText(_translate("Dialog", "Bienvenue"))
        self.label_2.setText(_translate("Dialog", "ParkingApp"))
        self.pushButto.setText(_translate("Dialog", "Démarrer"))
    ## acceder a principal
    def GoToPrincipal(self):
            self.window = QtWidgets.QTableWidget()
            self.ui = Ui_principale()
            self.window.setWindowIcon(QtGui.QIcon("interface\parking.png"))
            self.ui.setupUi(self.window)
           # Form.hide()
            self.window.show()
            MainWindow.hide()
if __name__ =="__main__":
                
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Dialog()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
